services:
  web:
    # Adjust this to expose whatever port you need for production to be public
    ports:
      - 8080:80

    # Adjust these based on your environment. All settings below are likely to
    # be needed in production environments where the database is external.
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - OJS_BASE_URL=http://localhost
      - OJS_ALLOWED_HOSTS=["localhost"]
      - OJS_SANDBOX=On
      - OJS_SALT=
      - OJS_API_KEY_SECRET=

    # This removes the db dependency so an external database can be used
    depends_on: !reset []
