# Example overrides for a dev environment, assuming you pull `ojs.compose.yaml`
# and `db.compose.yml` into your main compose file. This shows how your web
# environment might look in development.
#
# For a production setup, you will definitely not use this as-is. Some
# examples of what might change:
#
# - You might use an external database, so you'd have to specify the production
#   database env vars here and remove the "db" service
# - You should set HTTPS to "on" (and only allow secure traffic to the
#   container)
# - You really don't want a dependency on the smtpdebug service.
name: ojs
services:
  web:
    # Uncomment below to build an image with different PHP or OJS.
    #build:
    #  args:
    #    - PHP_VERSION=7.3
    #    - OJS_VERSION=3.3.0-8
    environment:
      HTTPS: "off"
      SERVER_PORT: "8080"
    ports:
      - 8080:80
    depends_on: &dev-deps
      - db
      - smtpdebug

    # Local volume example: this makes critical data volumes live on local disk
    # for easier editing, rsyncing, etc.
    volumes: &dev-vols
      - ./vols/private-files:/var/local/ojs-files
      - ./vols/public-files:/var/www/html/public
      - ./vols/plugins:/var/www/html/plugins
      - ./vols/config:/var/local/config

  # Technically for dev you can't actually use a worker unless you disable the
  # "sandbox" setting. Which is generally inadvisable for dev. So... proceed
  # with caution.
  worker:
    depends_on: *dev-deps
    volumes: *dev-vols

  db:
    ports:
      - 3306:3306
