services:
  web:
    # Adjust this to expose whatever port you need for production to be public
    ports:
      - 8080:80

    # Adjust these based on your environment. All settings below are likely to
    # be needed in production environments where the database is external.
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - OJS_BASE_URL=http://localhost
      - OJS_ALLOWED_HOSTS=["localhost"]
      - OJS_SANDBOX=On
      - OJS_SALT=
      - OJS_API_KEY_SECRET=

      # These are passed to Apache so that we can tell PHP (Symfony in
      # particular) that we're in a secure environment. The request URL is
      # using "https", generated URLs should be "https", etc.
      - SERVER_PORT=443
      - HTTPS=on
