name: ojs
services:
  web:
    build:
      context: .
    volumes:
      - private-files:/var/local/ojs-files
      - public-files:/var/www/html/public
      - plugins:/var/www/html/plugins
      - cache:/var/www/html/cache
      - config:/var/local/config
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - OJS_BASE_URL=http://localhost
      - OJS_ALLOWED_HOSTS=["localhost"]
      - OJS_SANDBOX=On
      - OJS_SALT=
      - OJS_API_KEY_SECRET=
      - HTTPS=
      - SERVER_PORT=

volumes:
  private-files:
  public-files:
  plugins:
  cache:
  config:
