# Example overrides for a dev environment, assuming you pull `ojs.compose.yaml`
# and `db.compose.yml` into your main compose file. This shows how your web
# environment might look in development, and includes the `init.sql.gz` file
# for the database to be initialized with a dummy admin user.
#
# For a production setup, you will definitely not use this as-is. Some
# examples of what might change:
#
# - You might use an external database, so you'd have to specify the production
#   database env vars here and remove the "db" service
# - Even if you do use a containerized database, you almost certainly don't
#   want to mount any SQL into it
# - You should set HTTPS to "on" (and only allow secure traffic to the
#   container)
services:
  web:
    environment:
      HTTPS: "off"
      SERVER_PORT: "8080"
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    ports:
      - 3306:3306
    volumes:
      - ./docker/init.sql.gz:/docker-entrypoint-initdb.d/init.sql.gz
