# Example overrides, assuming you pull `ojs.compose.yaml` and `db.compose.yml`
# into your main compose file
services:
  web:
    environment:
      OJS_BASE_URL: "http://localhost:8080"
      OJS_ALLOWED_HOSTS: '["localhost"]'
      OJS_SANDBOX: "On"
      OJS_SALT: "foo"
      OJS_API_KEY_SECRET: "bar"
      HTTPS: "off"
      SERVER_PORT: "8080"
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    ports:
      - 3306:3306
