services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: "ojs"
      MYSQL_USER: "ojs"
      MYSQL_PASSWORD: "ojs"
      MYSQL_ROOT_PASSWORD: "root_password"
    volumes:
      - db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
