services:
  web:
    build:
      context: .
      target: web
    volumes: &vols
      - private-files:/var/local/ojs-files
      - public-files:/var/www/html/public
      - plugins:/var/www/html/plugins
      - cache:/var/www/html/cache
      - config:/var/local/config
    environment:
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "ojs"
      MYSQL_USER: "ojs"
      MYSQL_PASSWORD: "ojs"
      HTTPS: ""
      SERVER_PORT: ""

  worker:
    build:
      context: .
      target: worker
    volumes: *vols
    environment:
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "ojs"
      MYSQL_USER: "ojs"
      MYSQL_PASSWORD: "ojs"

volumes:
  private-files:
  public-files:
  plugins:
  cache:
  config:
